### ISSUE TITLE
Writting string array in snirf file 

### ISSUE THREAD

**Issue by Edouard2laire** [NeuroJSON/jsnirfy#1]
Hello, 

First, thanks for having created this tool :). I was wondering how to use it to write snirf file. 
In particular, I have an issue with the encoding of text (see example bellow). For exemple, when writing the landmark labels, we create an array of string, but when reopening, this is transformed into 3D string array. 

I am doing something wrong or is it expected ? Other Software doesn't seems to accept the file with this formatting; 

Edouard

```
snirfdata = jsnirfcreate();
snirfdata.SNIRFData.metaDataTags.LengthUnit = 'm';

for i_landmark=1:10
    snirfdata.SNIRFData.probe.landmarkPos(i_landmark,:)= [0 0 0]';
    snirfdata.SNIRFData.probe.landmarkLabels(i_landmark)=string(sprintf('HP%d',i_landmark)); 
end
savesnirf(snirfdata, 'test.snirf');


jnirs2 = loadsnirf('test.snirf');
size(snirfdata.SNIRFData.probe.landmarkLabels) % 1    10
size(jnirs2.nirs.probe.landmarkLabels) % 1 4 10
disp(jnirs2.nirs.probe.landmarkLabels(:,:,1)) % HP1
```

I also try to open and write a valide file from the FRESH dataset and it seems that the string are not valide anymore: 

```
jnirs = loadsnirf('sub-05_ses-01_task-FRESHAUDIO_nirs.snirf');
savesnirf(jnirs, 'test_copy.snirf');
jnirs2 = loadsnirf('test_copy.snirf');
size(jnirs.nirs.probe.landmarkLabels)  % 130 1
size(jnirs2.nirs.probe.landmarkLabels) % 1 411
  jnirs2.nirs.probe.landmarkLabels % 'LPANASIONRPAHP_1HP_2HP_3HP_4HP_5HP_6HP_7HP_8HP_9HP_10HP_11HP_12HP_13HP_14HP_15HP_16HP_17HP_18HP_19HP_20HP_21HP_22HP_23HP_24HP_25HP_26HP_27HP_28HP_29HP_30HP_31HP_32HP_33Fp1FpzFp2AF9AF7AF5AF3AF1AFzAF2AF4AF6AF8AF10F9F7F5F3F1FzF2F4F6F8F10FT9FT7FC5FC3FC1FCzFC2FC4FC6FT8FT10T9T7C5C3C1CzC2C4C6T8T10TP9TP7CP5CP3CP1CPzCP2CP4CP6TP8TP10P9P7P5P3P1PzP2P4P6P8P10PO9PO7PO5PO3PO1POzPO2PO4PO6PO8PO10O1OzO2O9IzO10T3T5T4T6M1M2A1A2'

```

**Comment by Edouard2laire** [comment]
Hello; 

I hope you are ok. I was wondering if there was any news regarding that issue ? 

Thanks a lot, 
Edouard

**Comment by fangq** [comment]
@Edouard2laire, sorry for my late reply. ~~can you share the `sub-05_ses-01_task-FRESHAUDIO_nirs.snirf` file so I can test it? if it is big, you can put it in a dropbox/drive link. I can take a look~~

no need, I was able to reproduce the string change behavior and will debug it further.

**Comment by fangq** [comment]
@Edouard2laire, should work for your examples now. You need to update both easyh5 and jsnirfy to the latest github version.

I am also aware that `savesnirf` generated .snirf file can not pass the [pysnirf](https://pypi.org/project/pysnirf2/)  validator. This is because of the handling of strings. I am working on a fix to make those compatible.
